//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLC.Net.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HLC.Net.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Config_GamePath 的本地化字符串。
        /// </summary>
        public static string Config_GamePath {
            get {
                return ResourceManager.GetString("Config_GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config_Language 的本地化字符串。
        /// </summary>
        public static string Config_Language {
            get {
                return ResourceManager.GetString("Config_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content_ImageAutoResize 的本地化字符串。
        /// </summary>
        public static string Content_ImageAutoResize {
            get {
                return ResourceManager.GetString("Content_ImageAutoResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content_ImageHeight 的本地化字符串。
        /// </summary>
        public static string Content_ImageHeight {
            get {
                return ResourceManager.GetString("Content_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content_ImageMaxOut 的本地化字符串。
        /// </summary>
        public static string Content_ImageMaxOut {
            get {
                return ResourceManager.GetString("Content_ImageMaxOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content_ImageResize 的本地化字符串。
        /// </summary>
        public static string Content_ImageResize {
            get {
                return ResourceManager.GetString("Content_ImageResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content_ImageWidth 的本地化字符串。
        /// </summary>
        public static string Content_ImageWidth {
            get {
                return ResourceManager.GetString("Content_ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content_PixelCount 的本地化字符串。
        /// </summary>
        public static string Content_PixelCount {
            get {
                return ResourceManager.GetString("Content_PixelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content_UseSvenCoopLimite 的本地化字符串。
        /// </summary>
        public static string Content_UseSvenCoopLimite {
            get {
                return ResourceManager.GetString("Content_UseSvenCoopLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_About 的本地化字符串。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Exit 的本地化字符串。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Help 的本地化字符串。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu.OpenFile 的本地化字符串。
        /// </summary>
        public static string Menu_OpenFile {
            get {
                return ResourceManager.GetString("Menu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Option 的本地化字符串。
        /// </summary>
        public static string Menu_Option {
            get {
                return ResourceManager.GetString("Menu_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_SaveFile 的本地化字符串。
        /// </summary>
        public static string Menu_SaveFile {
            get {
                return ResourceManager.GetString("Menu_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message_NullImage 的本地化字符串。
        /// </summary>
        public static string Message_NullImage {
            get {
                return ResourceManager.GetString("Message_NullImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message_SaveDone 的本地化字符串。
        /// </summary>
        public static string Message_SaveDone {
            get {
                return ResourceManager.GetString("Message_SaveDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message_TooBigImage 的本地化字符串。
        /// </summary>
        public static string Message_TooBigImage {
            get {
                return ResourceManager.GetString("Message_TooBigImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate_Blur 的本地化字符串。
        /// </summary>
        public static string Operate_Blur {
            get {
                return ResourceManager.GetString("Operate_Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate_Bright 的本地化字符串。
        /// </summary>
        public static string Operate_Bright {
            get {
                return ResourceManager.GetString("Operate_Bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate_Constrast 的本地化字符串。
        /// </summary>
        public static string Operate_Constrast {
            get {
                return ResourceManager.GetString("Operate_Constrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate_Sharper 的本地化字符串。
        /// </summary>
        public static string Operate_Sharper {
            get {
                return ResourceManager.GetString("Operate_Sharper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate_Undo 的本地化字符串。
        /// </summary>
        public static string Operate_Undo {
            get {
                return ResourceManager.GetString("Operate_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_IsAlphaTest 的本地化字符串。
        /// </summary>
        public static string SaveOption_IsAlphaTest {
            get {
                return ResourceManager.GetString("SaveOption_IsAlphaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_Quntizater 的本地化字符串。
        /// </summary>
        public static string SaveOption_Quntizater {
            get {
                return ResourceManager.GetString("SaveOption_Quntizater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_Quntizater_Octree 的本地化字符串。
        /// </summary>
        public static string SaveOption_Quntizater_Octree {
            get {
                return ResourceManager.GetString("SaveOption_Quntizater_Octree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_Quntizater_Websafe 的本地化字符串。
        /// </summary>
        public static string SaveOption_Quntizater_Websafe {
            get {
                return ResourceManager.GetString("SaveOption_Quntizater_Websafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_Quntizater_Werner 的本地化字符串。
        /// </summary>
        public static string SaveOption_Quntizater_Werner {
            get {
                return ResourceManager.GetString("SaveOption_Quntizater_Werner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_Quntizater_Wu 的本地化字符串。
        /// </summary>
        public static string SaveOption_Quntizater_Wu {
            get {
                return ResourceManager.GetString("SaveOption_Quntizater_Wu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_SaveTo 的本地化字符串。
        /// </summary>
        public static string SaveOption_SaveTo {
            get {
                return ResourceManager.GetString("SaveOption_SaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveOption_SaveWithImage 的本地化字符串。
        /// </summary>
        public static string SaveOption_SaveWithImage {
            get {
                return ResourceManager.GetString("SaveOption_SaveWithImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 test 的本地化字符串。
        /// </summary>
        public static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HLC.Net 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
